# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:                                              # since Symfony 3.4
        mailer: app.custom_mailer    # since Symfony 3.4
    from_email:
        address: "info@fordealing.fr"
        sender_name: "FORDEALING"
    resetting:
        email:
            from_email:
                address:        "resetting@fordealing.fr"
                sender_name:    "FORDEALING"
            template:   'user/Mail/password_resetting_email.twig'
    registration:
        confirmation:
            template:   'user/Mail/registration_email.twig'
            enabled:    true
    profile:
        form:
            type: App\Form\User\ProfileType
fos_message:
    db_driver: orm
    thread_class: App\Entity\Message\Thread
    message_class: App\Entity\Message\Message
    new_thread_form:
        type:               App\Form\Message\NewThreadMessageFormType
        handler:            app_message.new_thread_form.handler # See FormHandler\NewThreadMessageFormHandler
        model:              App\Form\Message\NewThreadMessage