# config/packages/fos_user.yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:                                              # since Symfony 3.4
        mailer: fos_user.mailer.twig_swift    # since Symfony 3.4
    from_email:
        address: "info@onadaccord.fr"
        sender_name: "On a d'accord"
    resetting:
        email:
            from_email:
                address:        "resetting@onadaccord.fr"
                sender_name:    "On a d'accord"
            template:   'user/Resetting/email.txt.twig'
    registration:
        confirmation:
            template:   'user/Registration/email.txt.twig'
            enabled:    true
    profile:
        form:
            type: App\Form\ProfilType