twig:
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'PhotoType.html.twig'
        - 'RatingType.html.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/bundles/FOSMessageBundle': FOSMessageBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        form_offerSearchType: '@App\Service\Search\FormOfferType'
        form_demandSearchType: '@App\Service\Search\FormDemandType'
        form_DriverType: '@App\Service\FormDriverType'
        form_CityAreaType: '@App\Service\City\CityAreaType'
        form_CityAutoAreaType: '@App\Service\City\CityAutoAreaType'
        MessageCount: '@App\Service\Message\Message'





