twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        form_offerSearchType: '@App\Service\Search\FormOfferType'
        form_demandSearchType: '@App\Service\Search\FormDemandType'
        form_DriverType: '@App\Service\FormDriverType'



