twig:
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'PhotoType.html.twig'
        - 'RatingType.html.twig'
        - 'jquery.collection.html.twig'
        - 'StationCollectionType.html.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/bundles/FOSMessageBundle': FOSMessageBundle
        '%kernel.project_dir%/templates/admin/view/JMSJobQueue': JMSJobQueue
        '%kernel.project_dir%/templates/user': FOSUser
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locales: '%app.locales%'
        form_offerSearchType: '@App\Service\Search\FormOfferType'
        form_demandSearchType: '@App\Service\Search\FormDemandType'
        form_hostingSearchType: '@App\Service\Search\FormHostingSearchType'
        form_voyageSearchType: '@App\Service\Search\FormVoyageSearchType'
        form_meetupSearchType: '@App\Service\Search\FormMeetupSearchType'
        form_DriverType: '@App\Service\FormDriverType'
        form_HostingType: '@App\Service\FormHostingType'
        form_CityAreaType: '@App\Service\City\CityAreaType'
        form_CarpoolType: '@App\Service\FormCarpoolType'
        form_CityAutoAreaType: '@App\Service\City\CityAutoAreaType'
        MessageCount: '@App\Service\Message\Message'






