_translation_profiler:
  resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yml'
_translation_webui:
  resource: "@TranslationBundle/Resources/config/routing_webui.yml"
  prefix:  /admin/trans
