index:
    path: /
    controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
    path: /register
    controller: AppBundle\Controller\RegistrationController::registerAction

fos_user_resetting_request:
    path: /resetting/request
    controller: AppBundle\Controller\ResettingController::requestAction

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController::editAction
fos_user_profile_show:
    path: /profile
    controller: App\Controller\ProfileController::showAction