index:
    path: /
    controller: App\Controller\Ads\AdController::index
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
    path: /register
    controller: AppBundle\Controller\User\RegistrationController::registerAction

fos_user_resetting_request:
    path: /resetting/request
    controller: AppBundle\Controller\User\ResettingController::requestAction

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_edit:
    path: /profile/edit
    controller: App\Controller\User\ProfileController::editAction
fos_user_profile_show:
    path: /profile
    controller: App\Controller\User\ProfileController::showAction

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
