# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    adsimages: '%kernel.project_dir%/public/assets/images/annonce/'
    profileimages: '%kernel.project_dir%/public/assets/images/profile/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    redirect.after.login:
        class: App\Service\AfterLoginRedirection
        arguments: ['@router']

    app.form.registration:
        class: App\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.profile.form.type:
        class: App\Form\ProfilType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: app_user_profile }

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\RegistrationController:
        arguments:
            $formFactory: '@fos_user.registration.form.factory'
    App\Controller\ProfileController:
        arguments:
            $formFactory: '@fos_user.profile.form.factory'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%adsimages%'

    App\Form\EventListener\AddCategoryFieldSubscriber:
        arguments:
            $factory:

    App\Form\EventListener\AddGeneralcategoryFieldSubscriber:
        arguments:
            $factory:

    App\Form\EventListener\AddSpecificationFieldSubscriber:
        arguments:
            $factory:
            $entityManager:


